name: Build and deploy Node.js app to Azure Web App - MaritimeEdu

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build --if-present

      - name: Test project
        run: npm run test --if-present
      
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: |
            build  # Adjust if your build output directory is different
            server  # Adjust if your backend directory is different

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app

      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'MaritimeEdu'
          slot-name: 'Production'
          package: .

      - name: Set environment variables in Azure App Service
        run: |
          az webapp config appsettings set --name 'MaritimeEdu' --resource-group 'YourResourceGroupName' --settings MYSQL_HOST=${{ secrets.MYSQL_HOST }} MYSQL_USER=${{ secrets.MYSQL_USER }} MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }} MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE }}
        env:
          AZURE_WEBAPP_NAME: 'MaritimeEdu'
          AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
